FROM eclipse-temurin:21-jdk
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

ENV DB_DDL_AUTO=create

ENTRYPOINT ["java","-DDB_URL=${DB_URL}", "-DDB_USERNAME=${DB_USERNAME}", "-DDB_PASSWORD=${DB_PASSWORD}","-DDB_DDL_AUTO=${DB_DDL_AUTO}", "-DJWT_SECRET=${JWT_SECRET}", "-DJWT_VALID_TIME=${JWT_VALID_TIME}", "-jar", "app.jar"]

EXPOSE 3000
